g++ -c Main.cpp
g++ -c Product.cpp
g++ -c FileReader.cpp
g++ -c Location.cpp
g++ -c connection.cpp
g++ -c graphviewer.cpp
g++ -o main Main.o Product.o FileReader.o Location.o connection.o graphviewer.o
./main